In [2]:
#dependancies
import pandas as pd

# File to Load 
file_to_load = "../Data/Video_Games_Sales_Dec_2016.csv"

# Read file and store in a DF
game_data_df = pd.read_csv(file_to_load)

In [3]:
#check to see data has loaded
game_data_df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales (in millions),EU_Sales (in millions),JP_Sales (in millions),Other_Sales (in millions),Global_Sales (in millions),Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,1942,NES,1985.0,Shooter,Capcom,0.65,0.14,0.21,0.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN
1,Beyblade Burst,3DS,2016.0,Role-Playing,FuRyu,0.00,0.00,0.03,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN
2,Fire Emblem Fates,3DS,2015.0,Role-Playing,Nintendo,0.81,0.23,0.52,0.11,1.68,NaN,NaN,NaN,NaN,NaN,NaN
3,Frozen: Olaf's Quest,3DS,2013.0,Platform,Disney Interactive Studios,0.27,0.27,0.00,0.05,0.60,NaN,NaN,NaN,NaN,NaN,NaN
4,Frozen: Olaf's Quest,DS,2013.0,Platform,Disney Interactive Studios,0.21,0.26,0.00,0.04,0.52,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#drop all rows with missing data. Many of the older games are missing information like ratings
dupe_drop_df = game_data_df.dropna()
dupe_drop_df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales (in millions),EU_Sales (in millions),JP_Sales (in millions),Other_Sales (in millions),Global_Sales (in millions),Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
6,Tales of Xillia 2,PS3,2012.0,Role-Playing,Namco Bandai Games,0.20,0.12,0.45,0.07,0.84,71.0,59.0,7.9,216.0,Bandai Namco Games,T
12,.hack//Infection Part 1,PS2,2002.0,Role-Playing,Atari,0.49,0.38,0.26,0.13,1.27,75.0,35.0,8.5,60.0,CyberConnect2,T
14,.hack//Mutation Part 2,PS2,2002.0,Role-Playing,Atari,0.23,0.18,0.20,0.06,0.68,76.0,24.0,8.9,81.0,CyberConnect2,T
15,.hack//Outbreak Part 3,PS2,2002.0,Role-Playing,Atari,0.14,0.11,0.17,0.04,0.46,70.0,23.0,8.7,19.0,CyberConnect2,T
18,[Prototype 2],X360,2012.0,Action,Activision,0.48,0.24,0.00,0.07,0.79,74.0,69.0,7,173.0,Radical Entertainment,M

In [5]:
#dropping columns that are not needed. It will not help analysis to know how many votes there are in this instance
dropped_df = dupe_drop_df.drop(columns=['Critic_Count', 'User_Count'])
dropped_df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales (in millions),EU_Sales (in millions),JP_Sales (in millions),Other_Sales (in millions),Global_Sales (in millions),Critic_Score,User_Score,Developer,Rating
6,Tales of Xillia 2,PS3,2012.0,Role-Playing,Namco Bandai Games,0.20,0.12,0.45,0.07,0.84,71.0,7.9,Bandai Namco Games,T
12,.hack//Infection Part 1,PS2,2002.0,Role-Playing,Atari,0.49,0.38,0.26,0.13,1.27,75.0,8.5,CyberConnect2,T
14,.hack//Mutation Part 2,PS2,2002.0,Role-Playing,Atari,0.23,0.18,0.20,0.06,0.68,76.0,8.9,CyberConnect2,T
15,.hack//Outbreak Part 3,PS2,2002.0,Role-Playing,Atari,0.14,0.11,0.17,0.04,0.46,70.0,8.7,CyberConnect2,T
18,[Prototype 2],X360,2012.0,Action,Activision,0.48,0.24,0.00,0.07,0.79,74.0,7,Radical Entertainment,M

In [6]:
#user score was an object, converting to a useful format so I can multipy the values by 10 in line with the critic score
dropped_df['User_Score'] = dropped_df['User_Score'].astype(float)
dropped_df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales (in millions),EU_Sales (in millions),JP_Sales (in millions),Other_Sales (in millions),Global_Sales (in millions),Critic_Score,User_Score,Developer,Rating
6,Tales of Xillia 2,PS3,2012.0,Role-Playing,Namco Bandai Games,0.20,0.12,0.45,0.07,0.84,71.0,7.9,Bandai Namco Games,T
12,.hack//Infection Part 1,PS2,2002.0,Role-Playing,Atari,0.49,0.38,0.26,0.13,1.27,75.0,8.5,CyberConnect2,T
14,.hack//Mutation Part 2,PS2,2002.0,Role-Playing,Atari,0.23,0.18,0.20,0.06,0.68,76.0,8.9,CyberConnect2,T
15,.hack//Outbreak Part 3,PS2,2002.0,Role-Playing,Atari,0.14,0.11,0.17,0.04,0.46,70.0,8.7,CyberConnect2,T
18,[Prototype 2],X360,2012.0,Action,Activision,0.48,0.24,0.00,0.07,0.79,74.0,7.0,Radical Entertainment,M

In [7]:
dropped_df['User_Score'] = dropped_df['User_Score'] * 10
dropped_df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales (in millions),EU_Sales (in millions),JP_Sales (in millions),Other_Sales (in millions),Global_Sales (in millions),Critic_Score,User_Score,Developer,Rating
6,Tales of Xillia 2,PS3,2012.0,Role-Playing,Namco Bandai Games,0.20,0.12,0.45,0.07,0.84,71.0,79.0,Bandai Namco Games,T
12,.hack//Infection Part 1,PS2,2002.0,Role-Playing,Atari,0.49,0.38,0.26,0.13,1.27,75.0,85.0,CyberConnect2,T
14,.hack//Mutation Part 2,PS2,2002.0,Role-Playing,Atari,0.23,0.18,0.20,0.06,0.68,76.0,89.0,CyberConnect2,T
15,.hack//Outbreak Part 3,PS2,2002.0,Role-Playing,Atari,0.14,0.11,0.17,0.04,0.46,70.0,87.0,CyberConnect2,T
18,[Prototype 2],X360,2012.0,Action,Activision,0.48,0.24,0.00,0.07,0.79,74.0,70.0,Radical Entertainment,M

In [8]:
clean_videogame_data_df = dropped_df

In [9]:
#confirming that all numeric values are of the correct data types
clean_videogame_data_df.dtypes

Name                           object
Platform                       object
Year_of_Release               float64
Genre                          object
Publisher                      object
NA_Sales (in millions)        float64
EU_Sales (in millions)        float64
JP_Sales (in millions)        float64
Other_Sales (in millions)     float64
Global_Sales (in millions)    float64
Critic_Score                  float64
User_Score                    float64
Developer                      object
Rating                         object
dtype: object

In [10]:
# determining the name of the file
file_name = '../Data/clean_videogame_data.xlsx'
  
# saving the excel for excel analysis
clean_videogame_data_df.to_excel(file_name, index=False)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.

In [11]:
#saving as CSV for python analysis
file_name_1 = '../Data/clean_videogame_data_csv.csv'
clean_videogame_data_df.to_csv(file_name_1, index=False)